<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="1" total="53" passed="37" failed="15" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-10-03T15:27:41 GMT+03:00" name="Default suite" finished-at="2024-10-03T15:27:42 GMT+03:00" duration-ms="882">
    <groups>
    </groups>
    <test started-at="2024-10-03T15:27:41 GMT+03:00" name="Default test" finished-at="2024-10-03T15:27:42 GMT+03:00" duration-ms="882">
      <class name="MyTestCases">
        <test-method is-config="true" signature="mySetup()[pri:0, instance:MyTestCases@49e53c76]" started-at="2024-10-03T15:27:41 GMT+03:00" name="mySetup" finished-at="2024-10-03T15:27:41 GMT+03:00" duration-ms="505" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- mySetup -->
        <test-method signature="AddData()[pri:1, instance:MyTestCases@49e53c76]" started-at="2024-10-03T15:27:41 GMT+03:00" name="AddData" finished-at="2024-10-03T15:27:41 GMT+03:00" duration-ms="22" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddData -->
        <test-method signature="AddData()[pri:1, instance:MyTestCases@49e53c76]" started-at="2024-10-03T15:27:41 GMT+03:00" name="AddData" finished-at="2024-10-03T15:27:41 GMT+03:00" duration-ms="33" status="FAIL">
          <exception class="java.sql.SQLIntegrityConstraintViolationException">
            <message>
              <![CDATA[Duplicate entry '276' for key 'customers.PRIMARY']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '276' for key 'customers.PRIMARY'
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:118)
at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
at com.mysql.cj.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1334)
at com.mysql.cj.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2084)
at com.mysql.cj.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1245)
at MyTestCases.AddData(MyTestCases.java:43)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.sql.SQLIntegrityConstraintViolationException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddData -->
        <test-method signature="AddData()[pri:1, instance:MyTestCases@49e53c76]" started-at="2024-10-03T15:27:41 GMT+03:00" name="AddData" finished-at="2024-10-03T15:27:41 GMT+03:00" duration-ms="5" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddData -->
        <test-method signature="AddData()[pri:1, instance:MyTestCases@49e53c76]" started-at="2024-10-03T15:27:41 GMT+03:00" name="AddData" finished-at="2024-10-03T15:27:41 GMT+03:00" duration-ms="4" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddData -->
        <test-method signature="AddData()[pri:1, instance:MyTestCases@49e53c76]" started-at="2024-10-03T15:27:41 GMT+03:00" name="AddData" finished-at="2024-10-03T15:27:41 GMT+03:00" duration-ms="5" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddData -->
        <test-method signature="AddData()[pri:1, instance:MyTestCases@49e53c76]" started-at="2024-10-03T15:27:41 GMT+03:00" name="AddData" finished-at="2024-10-03T15:27:41 GMT+03:00" duration-ms="5" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddData -->
        <test-method signature="AddData()[pri:1, instance:MyTestCases@49e53c76]" started-at="2024-10-03T15:27:41 GMT+03:00" name="AddData" finished-at="2024-10-03T15:27:41 GMT+03:00" duration-ms="2" status="FAIL">
          <exception class="java.sql.SQLIntegrityConstraintViolationException">
            <message>
              <![CDATA[Duplicate entry '424' for key 'customers.PRIMARY']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '424' for key 'customers.PRIMARY'
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:118)
at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
at com.mysql.cj.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1334)
at com.mysql.cj.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2084)
at com.mysql.cj.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1245)
at MyTestCases.AddData(MyTestCases.java:43)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.sql.SQLIntegrityConstraintViolationException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddData -->
        <test-method signature="AddData()[pri:1, instance:MyTestCases@49e53c76]" started-at="2024-10-03T15:27:41 GMT+03:00" name="AddData" finished-at="2024-10-03T15:27:41 GMT+03:00" duration-ms="5" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddData -->
        <test-method signature="AddData()[pri:1, instance:MyTestCases@49e53c76]" started-at="2024-10-03T15:27:41 GMT+03:00" name="AddData" finished-at="2024-10-03T15:27:41 GMT+03:00" duration-ms="2" status="FAIL">
          <exception class="java.sql.SQLIntegrityConstraintViolationException">
            <message>
              <![CDATA[Duplicate entry '123' for key 'customers.PRIMARY']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '123' for key 'customers.PRIMARY'
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:118)
at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
at com.mysql.cj.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1334)
at com.mysql.cj.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2084)
at com.mysql.cj.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1245)
at MyTestCases.AddData(MyTestCases.java:43)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.sql.SQLIntegrityConstraintViolationException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddData -->
        <test-method signature="AddData()[pri:1, instance:MyTestCases@49e53c76]" started-at="2024-10-03T15:27:41 GMT+03:00" name="AddData" finished-at="2024-10-03T15:27:41 GMT+03:00" duration-ms="5" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddData -->
        <test-method signature="AddData()[pri:1, instance:MyTestCases@49e53c76]" started-at="2024-10-03T15:27:41 GMT+03:00" name="AddData" finished-at="2024-10-03T15:27:41 GMT+03:00" duration-ms="6" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddData -->
        <test-method signature="AddData()[pri:1, instance:MyTestCases@49e53c76]" started-at="2024-10-03T15:27:41 GMT+03:00" name="AddData" finished-at="2024-10-03T15:27:41 GMT+03:00" duration-ms="1" status="FAIL">
          <exception class="java.sql.SQLIntegrityConstraintViolationException">
            <message>
              <![CDATA[Duplicate entry '256' for key 'customers.PRIMARY']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '256' for key 'customers.PRIMARY'
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:118)
at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
at com.mysql.cj.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1334)
at com.mysql.cj.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2084)
at com.mysql.cj.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1245)
at MyTestCases.AddData(MyTestCases.java:43)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.sql.SQLIntegrityConstraintViolationException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddData -->
        <test-method signature="AddData()[pri:1, instance:MyTestCases@49e53c76]" started-at="2024-10-03T15:27:41 GMT+03:00" name="AddData" finished-at="2024-10-03T15:27:41 GMT+03:00" duration-ms="2" status="FAIL">
          <exception class="java.sql.SQLIntegrityConstraintViolationException">
            <message>
              <![CDATA[Duplicate entry '346' for key 'customers.PRIMARY']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '346' for key 'customers.PRIMARY'
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:118)
at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
at com.mysql.cj.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1334)
at com.mysql.cj.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2084)
at com.mysql.cj.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1245)
at MyTestCases.AddData(MyTestCases.java:43)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.sql.SQLIntegrityConstraintViolationException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddData -->
        <test-method signature="AddData()[pri:1, instance:MyTestCases@49e53c76]" started-at="2024-10-03T15:27:41 GMT+03:00" name="AddData" finished-at="2024-10-03T15:27:41 GMT+03:00" duration-ms="5" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddData -->
        <test-method signature="AddData()[pri:1, instance:MyTestCases@49e53c76]" started-at="2024-10-03T15:27:41 GMT+03:00" name="AddData" finished-at="2024-10-03T15:27:41 GMT+03:00" duration-ms="4" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddData -->
        <test-method signature="AddData()[pri:1, instance:MyTestCases@49e53c76]" started-at="2024-10-03T15:27:41 GMT+03:00" name="AddData" finished-at="2024-10-03T15:27:41 GMT+03:00" duration-ms="5" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddData -->
        <test-method signature="AddData()[pri:1, instance:MyTestCases@49e53c76]" started-at="2024-10-03T15:27:41 GMT+03:00" name="AddData" finished-at="2024-10-03T15:27:41 GMT+03:00" duration-ms="5" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddData -->
        <test-method signature="AddData()[pri:1, instance:MyTestCases@49e53c76]" started-at="2024-10-03T15:27:41 GMT+03:00" name="AddData" finished-at="2024-10-03T15:27:41 GMT+03:00" duration-ms="2" status="FAIL">
          <exception class="java.sql.SQLIntegrityConstraintViolationException">
            <message>
              <![CDATA[Duplicate entry '33' for key 'customers.PRIMARY']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '33' for key 'customers.PRIMARY'
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:118)
at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
at com.mysql.cj.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1334)
at com.mysql.cj.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2084)
at com.mysql.cj.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1245)
at MyTestCases.AddData(MyTestCases.java:43)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.sql.SQLIntegrityConstraintViolationException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddData -->
        <test-method signature="AddData()[pri:1, instance:MyTestCases@49e53c76]" started-at="2024-10-03T15:27:41 GMT+03:00" name="AddData" finished-at="2024-10-03T15:27:41 GMT+03:00" duration-ms="5" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddData -->
        <test-method signature="AddData()[pri:1, instance:MyTestCases@49e53c76]" started-at="2024-10-03T15:27:41 GMT+03:00" name="AddData" finished-at="2024-10-03T15:27:41 GMT+03:00" duration-ms="1" status="FAIL">
          <exception class="java.sql.SQLIntegrityConstraintViolationException">
            <message>
              <![CDATA[Duplicate entry '131' for key 'customers.PRIMARY']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '131' for key 'customers.PRIMARY'
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:118)
at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
at com.mysql.cj.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1334)
at com.mysql.cj.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2084)
at com.mysql.cj.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1245)
at MyTestCases.AddData(MyTestCases.java:43)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.sql.SQLIntegrityConstraintViolationException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddData -->
        <test-method signature="AddData()[pri:1, instance:MyTestCases@49e53c76]" started-at="2024-10-03T15:27:41 GMT+03:00" name="AddData" finished-at="2024-10-03T15:27:41 GMT+03:00" duration-ms="2" status="FAIL">
          <exception class="java.sql.SQLIntegrityConstraintViolationException">
            <message>
              <![CDATA[Duplicate entry '301' for key 'customers.PRIMARY']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '301' for key 'customers.PRIMARY'
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:118)
at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
at com.mysql.cj.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1334)
at com.mysql.cj.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2084)
at com.mysql.cj.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1245)
at MyTestCases.AddData(MyTestCases.java:43)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.sql.SQLIntegrityConstraintViolationException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddData -->
        <test-method signature="AddData()[pri:1, instance:MyTestCases@49e53c76]" started-at="2024-10-03T15:27:41 GMT+03:00" name="AddData" finished-at="2024-10-03T15:27:41 GMT+03:00" duration-ms="2" status="FAIL">
          <exception class="java.sql.SQLIntegrityConstraintViolationException">
            <message>
              <![CDATA[Duplicate entry '333' for key 'customers.PRIMARY']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '333' for key 'customers.PRIMARY'
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:118)
at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
at com.mysql.cj.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1334)
at com.mysql.cj.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2084)
at com.mysql.cj.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1245)
at MyTestCases.AddData(MyTestCases.java:43)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.sql.SQLIntegrityConstraintViolationException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddData -->
        <test-method signature="AddData()[pri:1, instance:MyTestCases@49e53c76]" started-at="2024-10-03T15:27:41 GMT+03:00" name="AddData" finished-at="2024-10-03T15:27:41 GMT+03:00" duration-ms="4" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddData -->
        <test-method signature="AddData()[pri:1, instance:MyTestCases@49e53c76]" started-at="2024-10-03T15:27:41 GMT+03:00" name="AddData" finished-at="2024-10-03T15:27:41 GMT+03:00" duration-ms="5" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddData -->
        <test-method signature="AddData()[pri:1, instance:MyTestCases@49e53c76]" started-at="2024-10-03T15:27:41 GMT+03:00" name="AddData" finished-at="2024-10-03T15:27:41 GMT+03:00" duration-ms="5" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddData -->
        <test-method signature="AddData()[pri:1, instance:MyTestCases@49e53c76]" started-at="2024-10-03T15:27:41 GMT+03:00" name="AddData" finished-at="2024-10-03T15:27:41 GMT+03:00" duration-ms="4" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddData -->
        <test-method signature="AddData()[pri:1, instance:MyTestCases@49e53c76]" started-at="2024-10-03T15:27:41 GMT+03:00" name="AddData" finished-at="2024-10-03T15:27:41 GMT+03:00" duration-ms="5" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddData -->
        <test-method signature="AddData()[pri:1, instance:MyTestCases@49e53c76]" started-at="2024-10-03T15:27:41 GMT+03:00" name="AddData" finished-at="2024-10-03T15:27:41 GMT+03:00" duration-ms="3" status="FAIL">
          <exception class="java.sql.SQLIntegrityConstraintViolationException">
            <message>
              <![CDATA[Duplicate entry '346' for key 'customers.PRIMARY']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '346' for key 'customers.PRIMARY'
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:118)
at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
at com.mysql.cj.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1334)
at com.mysql.cj.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2084)
at com.mysql.cj.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1245)
at MyTestCases.AddData(MyTestCases.java:43)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.sql.SQLIntegrityConstraintViolationException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddData -->
        <test-method signature="AddData()[pri:1, instance:MyTestCases@49e53c76]" started-at="2024-10-03T15:27:41 GMT+03:00" name="AddData" finished-at="2024-10-03T15:27:41 GMT+03:00" duration-ms="4" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddData -->
        <test-method signature="AddData()[pri:1, instance:MyTestCases@49e53c76]" started-at="2024-10-03T15:27:41 GMT+03:00" name="AddData" finished-at="2024-10-03T15:27:41 GMT+03:00" duration-ms="5" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddData -->
        <test-method signature="AddData()[pri:1, instance:MyTestCases@49e53c76]" started-at="2024-10-03T15:27:41 GMT+03:00" name="AddData" finished-at="2024-10-03T15:27:41 GMT+03:00" duration-ms="1" status="FAIL">
          <exception class="java.sql.SQLIntegrityConstraintViolationException">
            <message>
              <![CDATA[Duplicate entry '151' for key 'customers.PRIMARY']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '151' for key 'customers.PRIMARY'
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:118)
at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
at com.mysql.cj.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1334)
at com.mysql.cj.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2084)
at com.mysql.cj.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1245)
at MyTestCases.AddData(MyTestCases.java:43)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.sql.SQLIntegrityConstraintViolationException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddData -->
        <test-method signature="AddData()[pri:1, instance:MyTestCases@49e53c76]" started-at="2024-10-03T15:27:41 GMT+03:00" name="AddData" finished-at="2024-10-03T15:27:41 GMT+03:00" duration-ms="5" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddData -->
        <test-method signature="AddData()[pri:1, instance:MyTestCases@49e53c76]" started-at="2024-10-03T15:27:41 GMT+03:00" name="AddData" finished-at="2024-10-03T15:27:41 GMT+03:00" duration-ms="2" status="FAIL">
          <exception class="java.sql.SQLIntegrityConstraintViolationException">
            <message>
              <![CDATA[Duplicate entry '356' for key 'customers.PRIMARY']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '356' for key 'customers.PRIMARY'
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:118)
at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
at com.mysql.cj.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1334)
at com.mysql.cj.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2084)
at com.mysql.cj.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1245)
at MyTestCases.AddData(MyTestCases.java:43)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.sql.SQLIntegrityConstraintViolationException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddData -->
        <test-method signature="AddData()[pri:1, instance:MyTestCases@49e53c76]" started-at="2024-10-03T15:27:41 GMT+03:00" name="AddData" finished-at="2024-10-03T15:27:41 GMT+03:00" duration-ms="6" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddData -->
        <test-method signature="AddData()[pri:1, instance:MyTestCases@49e53c76]" started-at="2024-10-03T15:27:41 GMT+03:00" name="AddData" finished-at="2024-10-03T15:27:41 GMT+03:00" duration-ms="5" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddData -->
        <test-method signature="AddData()[pri:1, instance:MyTestCases@49e53c76]" started-at="2024-10-03T15:27:41 GMT+03:00" name="AddData" finished-at="2024-10-03T15:27:41 GMT+03:00" duration-ms="1" status="FAIL">
          <exception class="java.sql.SQLIntegrityConstraintViolationException">
            <message>
              <![CDATA[Duplicate entry '76' for key 'customers.PRIMARY']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '76' for key 'customers.PRIMARY'
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:118)
at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
at com.mysql.cj.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1334)
at com.mysql.cj.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2084)
at com.mysql.cj.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1245)
at MyTestCases.AddData(MyTestCases.java:43)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.sql.SQLIntegrityConstraintViolationException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddData -->
        <test-method signature="AddData()[pri:1, instance:MyTestCases@49e53c76]" started-at="2024-10-03T15:27:41 GMT+03:00" name="AddData" finished-at="2024-10-03T15:27:41 GMT+03:00" duration-ms="5" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddData -->
        <test-method signature="AddData()[pri:1, instance:MyTestCases@49e53c76]" started-at="2024-10-03T15:27:41 GMT+03:00" name="AddData" finished-at="2024-10-03T15:27:41 GMT+03:00" duration-ms="6" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddData -->
        <test-method signature="AddData()[pri:1, instance:MyTestCases@49e53c76]" started-at="2024-10-03T15:27:41 GMT+03:00" name="AddData" finished-at="2024-10-03T15:27:41 GMT+03:00" duration-ms="5" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddData -->
        <test-method signature="AddData()[pri:1, instance:MyTestCases@49e53c76]" started-at="2024-10-03T15:27:41 GMT+03:00" name="AddData" finished-at="2024-10-03T15:27:42 GMT+03:00" duration-ms="5" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddData -->
        <test-method signature="AddData()[pri:1, instance:MyTestCases@49e53c76]" started-at="2024-10-03T15:27:42 GMT+03:00" name="AddData" finished-at="2024-10-03T15:27:42 GMT+03:00" duration-ms="5" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddData -->
        <test-method signature="AddData()[pri:1, instance:MyTestCases@49e53c76]" started-at="2024-10-03T15:27:42 GMT+03:00" name="AddData" finished-at="2024-10-03T15:27:42 GMT+03:00" duration-ms="4" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddData -->
        <test-method signature="AddData()[pri:1, instance:MyTestCases@49e53c76]" started-at="2024-10-03T15:27:42 GMT+03:00" name="AddData" finished-at="2024-10-03T15:27:42 GMT+03:00" duration-ms="5" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddData -->
        <test-method signature="AddData()[pri:1, instance:MyTestCases@49e53c76]" started-at="2024-10-03T15:27:42 GMT+03:00" name="AddData" finished-at="2024-10-03T15:27:42 GMT+03:00" duration-ms="6" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddData -->
        <test-method signature="AddData()[pri:1, instance:MyTestCases@49e53c76]" started-at="2024-10-03T15:27:42 GMT+03:00" name="AddData" finished-at="2024-10-03T15:27:42 GMT+03:00" duration-ms="4" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddData -->
        <test-method signature="AddData()[pri:1, instance:MyTestCases@49e53c76]" started-at="2024-10-03T15:27:42 GMT+03:00" name="AddData" finished-at="2024-10-03T15:27:42 GMT+03:00" duration-ms="1" status="FAIL">
          <exception class="java.sql.SQLIntegrityConstraintViolationException">
            <message>
              <![CDATA[Duplicate entry '302' for key 'customers.PRIMARY']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '302' for key 'customers.PRIMARY'
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:118)
at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
at com.mysql.cj.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1334)
at com.mysql.cj.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2084)
at com.mysql.cj.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1245)
at MyTestCases.AddData(MyTestCases.java:43)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.sql.SQLIntegrityConstraintViolationException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddData -->
        <test-method signature="AddData()[pri:1, instance:MyTestCases@49e53c76]" started-at="2024-10-03T15:27:42 GMT+03:00" name="AddData" finished-at="2024-10-03T15:27:42 GMT+03:00" duration-ms="4" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddData -->
        <test-method signature="AddData()[pri:1, instance:MyTestCases@49e53c76]" started-at="2024-10-03T15:27:42 GMT+03:00" name="AddData" finished-at="2024-10-03T15:27:42 GMT+03:00" duration-ms="5" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddData -->
        <test-method signature="AddData()[pri:1, instance:MyTestCases@49e53c76]" started-at="2024-10-03T15:27:42 GMT+03:00" name="AddData" finished-at="2024-10-03T15:27:42 GMT+03:00" duration-ms="2" status="FAIL">
          <exception class="java.sql.SQLIntegrityConstraintViolationException">
            <message>
              <![CDATA[Duplicate entry '382' for key 'customers.PRIMARY']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '382' for key 'customers.PRIMARY'
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:118)
at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
at com.mysql.cj.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1334)
at com.mysql.cj.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2084)
at com.mysql.cj.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1245)
at MyTestCases.AddData(MyTestCases.java:43)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.sql.SQLIntegrityConstraintViolationException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddData -->
        <test-method signature="AddData()[pri:1, instance:MyTestCases@49e53c76]" started-at="2024-10-03T15:27:42 GMT+03:00" name="AddData" finished-at="2024-10-03T15:27:42 GMT+03:00" duration-ms="5" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddData -->
        <test-method signature="UpdateData()[pri:2, instance:MyTestCases@49e53c76]" started-at="2024-10-03T15:27:42 GMT+03:00" name="UpdateData" finished-at="2024-10-03T15:27:42 GMT+03:00" duration-ms="5" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- UpdateData -->
        <test-method signature="ReadData()[pri:3, instance:MyTestCases@49e53c76]" started-at="2024-10-03T15:27:42 GMT+03:00" name="ReadData" finished-at="2024-10-03T15:27:42 GMT+03:00" duration-ms="35" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ReadData -->
      </class> <!-- MyTestCases -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
